import 'package:flutter/material.dart';

/// Displays a structured execution plan generated by the agent in architect mode.
/// Shows step-by-step progress, affected files, risks, and action buttons.
class PlanningPanel extends StatefulWidget {
  final Map<String, dynamic> plan;
  final Map<String, String> stepStatuses;
  final bool isExecuting;
  final VoidCallback onApprove;
  final void Function(String) onModify;
  final VoidCallback onReject;
  final VoidCallback? onDismiss;

  const PlanningPanel({
    super.key,
    required this.plan,
    required this.stepStatuses,
    required this.isExecuting,
    required this.onApprove,
    required this.onModify,
    required this.onReject,
    this.onDismiss,
  });

  @override
  State<PlanningPanel> createState() => _PlanningPanelState();
}

class _PlanningPanelState extends State<PlanningPanel> {
  bool _isModifying = false;
  final _modifyController = TextEditingController();

  @override
  void dispose() {
    _modifyController.dispose();
    super.dispose();
  }

  List<Map<String, dynamic>> get _steps {
    final raw = widget.plan['steps'];
    if (raw is List) return raw.cast<Map<String, dynamic>>();
    return [];
  }

  List<Map<String, dynamic>> get _files {
    final raw = widget.plan['files'];
    if (raw is List) return raw.cast<Map<String, dynamic>>();
    return [];
  }

  List<String> get _risks {
    final raw = widget.plan['risks'];
    if (raw is List) return raw.cast<String>();
    return [];
  }

  List<String> get _questions {
    final raw = widget.plan['questions'];
    if (raw is List) return raw.cast<String>();
    return [];
  }

  bool get _hasAnyCompleted =>
      widget.stepStatuses.values.any((s) => s == 'completed');

  bool get _allCompleted =>
      _steps.isNotEmpty &&
      _steps.every((s) => widget.stepStatuses[s['id']] == 'completed');

  Color _statusBorderColor(ColorScheme colorScheme) {
    if (widget.isExecuting) return colorScheme.primary;
    if (_allCompleted) return Colors.green;
    if (_hasAnyCompleted) return colorScheme.primary;
    return Colors.amber;
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      margin: const EdgeInsets.symmetric(vertical: 4),
      decoration: BoxDecoration(
        color: _allCompleted
            ? Color.alphaBlend(Colors.green.withOpacity(0.04), colorScheme.surfaceContainerHigh)
            : colorScheme.surfaceContainerHigh,
        borderRadius: BorderRadius.zero,
        border: Border(
          left: BorderSide(color: _statusBorderColor(colorScheme), width: 3),
        ),
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisSize: MainAxisSize.min,
        children: [
          _buildHeader(theme),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 8),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if ((widget.plan['goal'] as String?)?.isNotEmpty ?? false) ...[
                  Text(
                    widget.plan['goal'] as String,
                    style: theme.textTheme.bodyMedium?.copyWith(
                      color: colorScheme.onSurface.withOpacity(0.75),
                    ),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 12),
                ],
                _buildStepsSummary(theme),
                if (_files.isNotEmpty) ...[
                  const SizedBox(height: 4),
                  _buildFilesSection(theme),
                ],
                if (_risks.isNotEmpty) ...[
                  const SizedBox(height: 4),
                  _buildCollapsibleList(
                    theme,
                    title: 'Risks & considerations',
                    icon: Icons.warning_amber_rounded,
                    iconColor: colorScheme.error,
                    items: _risks,
                  ),
                ],
                if (_questions.isNotEmpty) ...[
                  const SizedBox(height: 4),
                  _buildCollapsibleList(
                    theme,
                    title: 'Clarifications needed',
                    icon: Icons.help_outline,
                    iconColor: colorScheme.primary,
                    items: _questions,
                  ),
                ],
                const SizedBox(height: 8),
                if (_isModifying) _buildModifyInput(theme) else _buildActionRow(theme),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHeader(ThemeData theme) {
    final colorScheme = theme.colorScheme;
    final title = widget.plan['title'] as String? ?? 'Execution Plan';

    String statusLabel;
    Color statusColor;
    if (widget.isExecuting) {
      statusLabel = 'Executing…';
      statusColor = colorScheme.primary;
    } else if (_allCompleted) {
      statusLabel = 'Built ✓';
      statusColor = Colors.green;
    } else if (_hasAnyCompleted) {
      statusLabel = 'In Progress';
      statusColor = colorScheme.primary;
    } else {
      statusLabel = 'Pending Approval';
      statusColor = Colors.amber;
    }

    return Container(
      padding: const EdgeInsets.fromLTRB(16, 12, 12, 8),
      decoration: BoxDecoration(
        border: Border(
          bottom: BorderSide(color: colorScheme.outline.withOpacity(0.15)),
        ),
      ),
      child: Row(
        children: [
          Icon(Icons.checklist, size: 16, color: colorScheme.primary),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              title,
              style: theme.textTheme.titleSmall?.copyWith(
                fontWeight: FontWeight.bold,
              ),
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
            decoration: BoxDecoration(
              color: statusColor.withOpacity(0.12),
              borderRadius: BorderRadius.zero,
              border: Border.all(color: statusColor.withOpacity(0.3)),
            ),
            child: Text(
              statusLabel,
              style: theme.textTheme.labelSmall?.copyWith(
                color: statusColor,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  bool _stepsExpanded = false;

  Widget _buildStepsSummary(ThemeData theme) {
    if (_steps.isEmpty) return const SizedBox.shrink();
    final colorScheme = theme.colorScheme;
    final completed = _steps.where((s) => widget.stepStatuses[s['id']] == 'completed').length;
    final total = _steps.length;
    final hasStarted = _hasAnyCompleted || _steps.any((s) => widget.stepStatuses[s['id']] == 'in_progress');
    final summary = hasStarted || _allCompleted
        ? '$completed of $total To-dos Completed'
        : '$total To-do${total != 1 ? 's' : ''}';

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 3),
              decoration: BoxDecoration(
                color: _allCompleted
                    ? Colors.green.withOpacity(0.1)
                    : colorScheme.surfaceContainerHighest,
                borderRadius: BorderRadius.zero,
                border: _allCompleted
                    ? Border.all(color: Colors.green.withOpacity(0.2))
                    : null,
              ),
              child: Text(
                summary,
                style: theme.textTheme.labelSmall?.copyWith(
                  color: _allCompleted ? Colors.green : colorScheme.onSurface.withOpacity(0.6),
                ),
              ),
            ),
            const Spacer(),
            GestureDetector(
              onTap: () => setState(() => _stepsExpanded = !_stepsExpanded),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    _stepsExpanded ? 'View Less' : 'View Plan',
                    style: theme.textTheme.labelSmall?.copyWith(
                      color: colorScheme.primary,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                  Icon(
                    _stepsExpanded ? Icons.keyboard_arrow_down : Icons.chevron_right,
                    size: 14,
                    color: colorScheme.primary,
                  ),
                ],
              ),
            ),
          ],
        ),
        if (_stepsExpanded) ...[
          const SizedBox(height: 8),
          _buildStepsList(theme),
        ],
      ],
    );
  }

  Widget _buildStepsList(ThemeData theme) {
    if (_steps.isEmpty) return const SizedBox.shrink();
    final colorScheme = theme.colorScheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Steps',
          style: theme.textTheme.labelMedium?.copyWith(
            color: colorScheme.onSurface.withOpacity(0.6),
            fontWeight: FontWeight.w600,
          ),
        ),
        const SizedBox(height: 6),
        ..._steps.map((step) => _buildStepTile(theme, step)),
      ],
    );
  }

  Widget _buildStepTile(ThemeData theme, Map<String, dynamic> step) {
    final colorScheme = theme.colorScheme;
    final stepId = step['id'] as String? ?? '';
    final status = widget.stepStatuses[stepId] ?? 'pending';
    final title = step['title'] as String? ?? 'Step $stepId';
    final description = step['description'] as String?;

    Widget leadingIcon;
    Color iconColor;
    switch (status) {
      case 'completed':
        leadingIcon = const Icon(Icons.check_circle, size: 18);
        iconColor = Colors.green;
        break;
      case 'in_progress':
        leadingIcon = SizedBox(
          width: 18,
          height: 18,
          child: CircularProgressIndicator(strokeWidth: 2, color: colorScheme.primary),
        );
        iconColor = colorScheme.primary;
        break;
      case 'failed':
        leadingIcon = const Icon(Icons.error, size: 18);
        iconColor = colorScheme.error;
        break;
      default:
        leadingIcon = Icon(Icons.radio_button_unchecked, size: 18, color: colorScheme.onSurface.withOpacity(0.35));
        iconColor = colorScheme.onSurface.withOpacity(0.35);
    }

    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: description != null && description.isNotEmpty
          ? ExpansionTile(
              leading: IconTheme(
                data: IconThemeData(color: iconColor),
                child: leadingIcon,
              ),
              title: Text(
                title,
                style: theme.textTheme.bodyMedium?.copyWith(
                  fontWeight: status == 'completed' ? FontWeight.normal : FontWeight.w500,
                  color: status == 'completed'
                      ? colorScheme.onSurface.withOpacity(0.5)
                      : colorScheme.onSurface,
                  decoration: status == 'completed' ? TextDecoration.lineThrough : null,
                ),
              ),
              tilePadding: const EdgeInsets.symmetric(horizontal: 4),
              childrenPadding: const EdgeInsets.fromLTRB(28, 0, 4, 8),
              children: [
                Text(
                  description,
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: colorScheme.onSurface.withOpacity(0.7),
                  ),
                ),
              ],
            )
          : ListTile(
              leading: IconTheme(
                data: IconThemeData(color: iconColor),
                child: leadingIcon,
              ),
              title: Text(
                title,
                style: theme.textTheme.bodyMedium?.copyWith(
                  fontWeight: status == 'completed' ? FontWeight.normal : FontWeight.w500,
                  color: status == 'completed'
                      ? colorScheme.onSurface.withOpacity(0.5)
                      : colorScheme.onSurface,
                  decoration: status == 'completed' ? TextDecoration.lineThrough : null,
                ),
              ),
              contentPadding: const EdgeInsets.symmetric(horizontal: 4),
              dense: true,
            ),
    );
  }

  Widget _buildFilesSection(ThemeData theme) {
    final colorScheme = theme.colorScheme;

    return ExpansionTile(
      leading: Icon(Icons.folder_open, size: 18, color: colorScheme.onSurface.withOpacity(0.6)),
      title: Text(
        'Files affected (${_files.length})',
        style: theme.textTheme.labelMedium?.copyWith(
          color: colorScheme.onSurface.withOpacity(0.6),
          fontWeight: FontWeight.w600,
        ),
      ),
      tilePadding: EdgeInsets.zero,
      childrenPadding: const EdgeInsets.fromLTRB(4, 0, 4, 8),
      children: _files.map((f) {
        final path = f['path'] as String? ?? '';
        final action = f['action'] as String? ?? 'modify';
        final reason = f['reason'] as String?;

        Color actionColor;
        switch (action) {
          case 'create':
            actionColor = Colors.green;
            break;
          case 'delete':
            actionColor = colorScheme.error;
            break;
          default:
            actionColor = colorScheme.primary;
        }

        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 3),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                decoration: BoxDecoration(
                  color: actionColor.withOpacity(0.12),
                  borderRadius: BorderRadius.zero,
                ),
                child: Text(
                  action,
                  style: theme.textTheme.labelSmall?.copyWith(
                    color: actionColor,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      path,
                      style: theme.textTheme.bodySmall?.copyWith(
                        fontFamily: 'monospace',
                      ),
                      overflow: TextOverflow.ellipsis,
                    ),
                    if (reason != null && reason.isNotEmpty)
                      Text(
                        reason,
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: colorScheme.onSurface.withOpacity(0.55),
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                  ],
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  Widget _buildCollapsibleList(
    ThemeData theme, {
    required String title,
    required IconData icon,
    required Color iconColor,
    required List<String> items,
  }) {
    final colorScheme = theme.colorScheme;

    return ExpansionTile(
      leading: Icon(icon, size: 18, color: iconColor),
      title: Text(
        title,
        style: theme.textTheme.labelMedium?.copyWith(
          color: colorScheme.onSurface.withOpacity(0.6),
          fontWeight: FontWeight.w600,
        ),
      ),
      tilePadding: EdgeInsets.zero,
      childrenPadding: const EdgeInsets.fromLTRB(4, 0, 4, 8),
      children: items
          .map(
            (item) => Padding(
              padding: const EdgeInsets.symmetric(vertical: 3),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('• ', style: theme.textTheme.bodySmall?.copyWith(color: iconColor)),
                  Expanded(
                    child: Text(item, style: theme.textTheme.bodySmall),
                  ),
                ],
              ),
            ),
          )
          .toList(),
    );
  }

  Widget _buildActionRow(ThemeData theme) {
    final hasStarted = _hasAnyCompleted;
    // Only show Dismiss during partial execution, not after all steps are complete
    final showDismiss = hasStarted && !_allCompleted && !widget.isExecuting && widget.onDismiss != null;

    // No action buttons when all done — card persists as a record
    if (_allCompleted && !widget.isExecuting) {
      return const SizedBox.shrink();
    }

    return Row(
      children: [
        if (!widget.isExecuting && !hasStarted) ...[
          FilledButton.icon(
            onPressed: () => widget.onApprove(),
            icon: const Icon(Icons.play_arrow, size: 16),
            label: const Text('Approve'),
          ),
          const SizedBox(width: 8),
          OutlinedButton.icon(
            onPressed: () => setState(() => _isModifying = true),
            icon: const Icon(Icons.edit, size: 16),
            label: const Text('Modify'),
          ),
          const SizedBox(width: 8),
          TextButton(
            onPressed: widget.onReject,
            child: const Text('Reject'),
          ),
        ],
        if (widget.isExecuting)
          TextButton.icon(
            onPressed: null,
            icon: SizedBox(
              width: 14,
              height: 14,
              child: CircularProgressIndicator(
                strokeWidth: 2,
                color: theme.colorScheme.primary.withOpacity(0.5),
              ),
            ),
            label: const Text('Executing...'),
          ),
        if (showDismiss)
          OutlinedButton.icon(
            onPressed: widget.onDismiss,
            icon: const Icon(Icons.check_circle_outline, size: 16),
            label: const Text('Done'),
          ),
      ],
    );
  }

  Widget _buildModifyInput(ThemeData theme) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TextField(
          controller: _modifyController,
          decoration: InputDecoration(
            hintText: 'Describe what to change in the plan...',
            border: const OutlineInputBorder(),
            isDense: true,
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          ),
          maxLines: 3,
          minLines: 2,
          autofocus: true,
        ),
        const SizedBox(height: 8),
        Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            TextButton(
              onPressed: () => setState(() {
                _isModifying = false;
                _modifyController.clear();
              }),
              child: const Text('Cancel'),
            ),
            const SizedBox(width: 8),
            FilledButton(
              onPressed: () {
                final instruction = _modifyController.text.trim();
                if (instruction.isEmpty) return;
                widget.onModify('Please modify the plan: $instruction');
                _modifyController.clear();
                setState(() => _isModifying = false);
              },
              child: const Text('Send'),
            ),
          ],
        ),
      ],
    );
  }
}
